trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    name: Build
    inputs:
      command: 'build'

  - task: DotNetCoreCLI@2
    name: Test
    inputs:
      command: 'test'