trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'book-01/*'

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

steps:
  - task: DotNetCoreCLI@2
    name: Build
    inputs:
      command: 'build'
      projects:  '**/*.csproj'

  - task: DotNetCoreCLI@2
    name: Test
    inputs:
      command: 'test'
      projects:  '**/*.Test.csproj'